controller_manager:
  ros__parameters:
    update_rate: 30.0
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    skid_cont:
      type: skid_steer_controller/SkidSteerController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 30.0
    
    left_wheel_names: ['left_front']
    right_wheel_names: ['right_front']
    wheel_separation: 0.22
    wheel_radius: 0.05

    use_stamped_vel: false

    base_frame_id: base_link
    odom_frame_id: odom

    enable_odom_tf: true
